/* soapMedia2BindingService.h
   Generated by gSOAP 2.8.17r from onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapMedia2BindingService_H
#define soapMedia2BindingService_H
#include "soapH.h"
class SOAP_CMAC Media2BindingService
{ public:
	struct soap *soap;
	bool own;
	/// Constructor
	Media2BindingService();
	/// Constructor to use/share an engine state
	Media2BindingService(struct soap*);
	/// Constructor with engine input+output mode control
	Media2BindingService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	Media2BindingService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~Media2BindingService();
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to defaults
	virtual	void reset();
	/// Initializer used by constructor
	virtual	void Media2BindingService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	Media2BindingService *copy() SOAP_PURE_VIRTUAL;
	/// Close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Then accept SSL handshake, when SSL is used
	virtual	int ssl_accept();
#endif
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_ns9__GetServiceCapabilities *ns9__GetServiceCapabilities, _ns9__GetServiceCapabilitiesResponse *ns9__GetServiceCapabilitiesResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'CreateProfile' (returns error code or SOAP_OK)
	virtual	int CreateProfile(_ns9__CreateProfile *ns9__CreateProfile, _ns9__CreateProfileResponse *ns9__CreateProfileResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetProfiles' (returns error code or SOAP_OK)
	virtual	int GetProfiles(_ns9__GetProfiles *ns9__GetProfiles, _ns9__GetProfilesResponse *ns9__GetProfilesResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'AddConfiguration' (returns error code or SOAP_OK)
	virtual	int AddConfiguration(_ns9__AddConfiguration *ns9__AddConfiguration, _ns9__AddConfigurationResponse *ns9__AddConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'RemoveConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveConfiguration(_ns9__RemoveConfiguration *ns9__RemoveConfiguration, _ns9__RemoveConfigurationResponse *ns9__RemoveConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DeleteProfile' (returns error code or SOAP_OK)
	virtual	int DeleteProfile(_ns9__DeleteProfile *ns9__DeleteProfile, _ns9__DeleteProfileResponse *ns9__DeleteProfileResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetVideoSourceConfigurations' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfigurations(ns9__GetConfiguration *ns9__GetVideoSourceConfigurations, _ns9__GetVideoSourceConfigurationsResponse *ns9__GetVideoSourceConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetVideoEncoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetVideoEncoderConfigurations(ns9__GetConfiguration *ns9__GetVideoEncoderConfigurations, _ns9__GetVideoEncoderConfigurationsResponse *ns9__GetVideoEncoderConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioSourceConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfigurations(ns9__GetConfiguration *ns9__GetAudioSourceConfigurations, _ns9__GetAudioSourceConfigurationsResponse *ns9__GetAudioSourceConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioEncoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioEncoderConfigurations(ns9__GetConfiguration *ns9__GetAudioEncoderConfigurations, _ns9__GetAudioEncoderConfigurationsResponse *ns9__GetAudioEncoderConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAnalyticsConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAnalyticsConfigurations(ns9__GetConfiguration *ns9__GetAnalyticsConfigurations, _ns9__GetAnalyticsConfigurationsResponse *ns9__GetAnalyticsConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetMetadataConfigurations' (returns error code or SOAP_OK)
	virtual	int GetMetadataConfigurations(ns9__GetConfiguration *ns9__GetMetadataConfigurations, _ns9__GetMetadataConfigurationsResponse *ns9__GetMetadataConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioOutputConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfigurations(ns9__GetConfiguration *ns9__GetAudioOutputConfigurations, _ns9__GetAudioOutputConfigurationsResponse *ns9__GetAudioOutputConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioDecoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioDecoderConfigurations(ns9__GetConfiguration *ns9__GetAudioDecoderConfigurations, _ns9__GetAudioDecoderConfigurationsResponse *ns9__GetAudioDecoderConfigurationsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoSourceConfiguration(_ns9__SetVideoSourceConfiguration *ns9__SetVideoSourceConfiguration, ns9__SetConfigurationResponse *ns9__SetVideoSourceConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetVideoEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoEncoderConfiguration(_ns9__SetVideoEncoderConfiguration *ns9__SetVideoEncoderConfiguration, ns9__SetConfigurationResponse *ns9__SetVideoEncoderConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioSourceConfiguration(_ns9__SetAudioSourceConfiguration *ns9__SetAudioSourceConfiguration, ns9__SetConfigurationResponse *ns9__SetAudioSourceConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetAudioEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioEncoderConfiguration(_ns9__SetAudioEncoderConfiguration *ns9__SetAudioEncoderConfiguration, ns9__SetConfigurationResponse *ns9__SetAudioEncoderConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetMetadataConfiguration' (returns error code or SOAP_OK)
	virtual	int SetMetadataConfiguration(_ns9__SetMetadataConfiguration *ns9__SetMetadataConfiguration, ns9__SetConfigurationResponse *ns9__SetMetadataConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioOutputConfiguration(_ns9__SetAudioOutputConfiguration *ns9__SetAudioOutputConfiguration, ns9__SetConfigurationResponse *ns9__SetAudioOutputConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetAudioDecoderConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioDecoderConfiguration(_ns9__SetAudioDecoderConfiguration *ns9__SetAudioDecoderConfiguration, ns9__SetConfigurationResponse *ns9__SetAudioDecoderConfigurationResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetVideoSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfigurationOptions(ns9__GetConfiguration *ns9__GetVideoSourceConfigurationOptions, _ns9__GetVideoSourceConfigurationOptionsResponse *ns9__GetVideoSourceConfigurationOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetVideoEncoderConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoEncoderConfigurationOptions(ns9__GetConfiguration *ns9__GetVideoEncoderConfigurationOptions, _ns9__GetVideoEncoderConfigurationOptionsResponse *ns9__GetVideoEncoderConfigurationOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfigurationOptions(ns9__GetConfiguration *ns9__GetAudioSourceConfigurationOptions, _ns9__GetAudioSourceConfigurationOptionsResponse *ns9__GetAudioSourceConfigurationOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioEncoderConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioEncoderConfigurationOptions(ns9__GetConfiguration *ns9__GetAudioEncoderConfigurationOptions, _ns9__GetAudioEncoderConfigurationOptionsResponse *ns9__GetAudioEncoderConfigurationOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetMetadataConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetMetadataConfigurationOptions(ns9__GetConfiguration *ns9__GetMetadataConfigurationOptions, _ns9__GetMetadataConfigurationOptionsResponse *ns9__GetMetadataConfigurationOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioOutputConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfigurationOptions(ns9__GetConfiguration *ns9__GetAudioOutputConfigurationOptions, _ns9__GetAudioOutputConfigurationOptionsResponse *ns9__GetAudioOutputConfigurationOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetAudioDecoderConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioDecoderConfigurationOptions(ns9__GetConfiguration *ns9__GetAudioDecoderConfigurationOptions, _ns9__GetAudioDecoderConfigurationOptionsResponse *ns9__GetAudioDecoderConfigurationOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetVideoEncoderInstances' (returns error code or SOAP_OK)
	virtual	int GetVideoEncoderInstances(_ns9__GetVideoEncoderInstances *ns9__GetVideoEncoderInstances, _ns9__GetVideoEncoderInstancesResponse *ns9__GetVideoEncoderInstancesResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetStreamUri' (returns error code or SOAP_OK)
	virtual	int GetStreamUri(_ns9__GetStreamUri *ns9__GetStreamUri, _ns9__GetStreamUriResponse *ns9__GetStreamUriResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'StartMulticastStreaming' (returns error code or SOAP_OK)
	virtual	int StartMulticastStreaming(ns9__StartStopMulticastStreaming *ns9__StartMulticastStreaming, ns9__SetConfigurationResponse *ns9__StartMulticastStreamingResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'StopMulticastStreaming' (returns error code or SOAP_OK)
	virtual	int StopMulticastStreaming(ns9__StartStopMulticastStreaming *ns9__StopMulticastStreaming, ns9__SetConfigurationResponse *ns9__StopMulticastStreamingResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetSynchronizationPoint' (returns error code or SOAP_OK)
	virtual	int SetSynchronizationPoint(_ns9__SetSynchronizationPoint *ns9__SetSynchronizationPoint, _ns9__SetSynchronizationPointResponse *ns9__SetSynchronizationPointResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetSnapshotUri' (returns error code or SOAP_OK)
	virtual	int GetSnapshotUri(_ns9__GetSnapshotUri *ns9__GetSnapshotUri, _ns9__GetSnapshotUriResponse *ns9__GetSnapshotUriResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetVideoSourceModes' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceModes(_ns9__GetVideoSourceModes *ns9__GetVideoSourceModes, _ns9__GetVideoSourceModesResponse *ns9__GetVideoSourceModesResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetVideoSourceMode' (returns error code or SOAP_OK)
	virtual	int SetVideoSourceMode(_ns9__SetVideoSourceMode *ns9__SetVideoSourceMode, _ns9__SetVideoSourceModeResponse *ns9__SetVideoSourceModeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetOSDs' (returns error code or SOAP_OK)
	virtual	int GetOSDs(_ns9__GetOSDs *ns9__GetOSDs, _ns9__GetOSDsResponse *ns9__GetOSDsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetOSDOptions' (returns error code or SOAP_OK)
	virtual	int GetOSDOptions(_ns9__GetOSDOptions *ns9__GetOSDOptions, _ns9__GetOSDOptionsResponse *ns9__GetOSDOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetOSD' (returns error code or SOAP_OK)
	virtual	int SetOSD(_ns9__SetOSD *ns9__SetOSD, ns9__SetConfigurationResponse *ns9__SetOSDResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'CreateOSD' (returns error code or SOAP_OK)
	virtual	int CreateOSD(_ns9__CreateOSD *ns9__CreateOSD, _ns9__CreateOSDResponse *ns9__CreateOSDResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DeleteOSD' (returns error code or SOAP_OK)
	virtual	int DeleteOSD(_ns9__DeleteOSD *ns9__DeleteOSD, ns9__SetConfigurationResponse *ns9__DeleteOSDResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetMasks' (returns error code or SOAP_OK)
	virtual	int GetMasks(_ns9__GetMasks *ns9__GetMasks, _ns9__GetMasksResponse *ns9__GetMasksResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetMaskOptions' (returns error code or SOAP_OK)
	virtual	int GetMaskOptions(_ns9__GetMaskOptions *ns9__GetMaskOptions, _ns9__GetMaskOptionsResponse *ns9__GetMaskOptionsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SetMask' (returns error code or SOAP_OK)
	virtual	int SetMask(_ns9__SetMask *ns9__SetMask, ns9__SetConfigurationResponse *ns9__SetMaskResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'CreateMask' (returns error code or SOAP_OK)
	virtual	int CreateMask(_ns9__CreateMask *ns9__CreateMask, _ns9__CreateMaskResponse *ns9__CreateMaskResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DeleteMask' (returns error code or SOAP_OK)
	virtual	int DeleteMask(_ns9__DeleteMask *ns9__DeleteMask, ns9__SetConfigurationResponse *ns9__DeleteMaskResponse) SOAP_PURE_VIRTUAL;
};
#endif
