/* soapAuthenticationBehaviorBindingProxy.cpp
   Generated by gSOAP 2.8.17r from onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapAuthenticationBehaviorBindingProxy.h"

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy()
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	AuthenticationBehaviorBindingProxy_init(_soap->imode, _soap->omode);
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingProxy_init(iomode, iomode);
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingProxy_init(imode, omode);
}

AuthenticationBehaviorBindingProxy::~AuthenticationBehaviorBindingProxy()
{	if (this->own)
		soap_free(this->soap);
}

void AuthenticationBehaviorBindingProxy::AuthenticationBehaviorBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
	{"wsc", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns2", "http://www.onvif.org/ver10/pacs", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"name", "http://www.onvif.org/ver10/advancedsecurity/wsdl/AdvancedSecurityServiceBinding", NULL, NULL},
	{"name10", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
	{"name11", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
	{"name12", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
	{"name13", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
	{"name14", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"name2", "http://www.onvif.org/ver10/advancedsecurity/wsdl/KeystoreBinding", NULL, NULL},
	{"name3", "http://www.onvif.org/ver10/advancedsecurity/wsdl/TLSServerBinding", NULL, NULL},
	{"name4", "http://www.onvif.org/ver10/advancedsecurity/wsdl/Dot1XBinding", NULL, NULL},
	{"ns5", "http://www.onvif.org/ver10/advancedsecurity/wsdl", NULL, NULL},
	{"name5", "http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding", NULL, NULL},
	{"name6", "http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"name7", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
	{"name8", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"name9", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
	{"ns1", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
	{"ns10", "http://www.onvif.org/ver10/provisioning/wsdl", NULL, NULL},
	{"ns11", "http://www.onvif.org/ver10/schedule/wsdl", NULL, NULL},
	{"ns12", "http://www.onvif.org/ver10/thermal/wsdl", NULL, NULL},
	{"ns3", "http://www.onvif.org/ver10/accessrules/wsdl", NULL, NULL},
	{"ns4", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
	{"ns6", "http://www.onvif.org/ver10/authenticationbehavior/wsdl", NULL, NULL},
	{"ns7", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
	{"ns8", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
	{"ns9", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
	{"tad", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
	{"tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
	{"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
	{"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void AuthenticationBehaviorBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void AuthenticationBehaviorBindingProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	AuthenticationBehaviorBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void AuthenticationBehaviorBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void AuthenticationBehaviorBindingProxy::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
	this->soap->header->wsse__Security = wsse__Security;
}

const SOAP_ENV__Header *AuthenticationBehaviorBindingProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *AuthenticationBehaviorBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *AuthenticationBehaviorBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *AuthenticationBehaviorBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int AuthenticationBehaviorBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int AuthenticationBehaviorBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void AuthenticationBehaviorBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void AuthenticationBehaviorBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *AuthenticationBehaviorBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int AuthenticationBehaviorBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns6__GetServiceCapabilities *ns6__GetServiceCapabilities, _ns6__GetServiceCapabilitiesResponse *ns6__GetServiceCapabilitiesResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetServiceCapabilities soap_tmp___ns6__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetServiceCapabilities";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetServiceCapabilities.ns6__GetServiceCapabilities = ns6__GetServiceCapabilities;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities, "-ns6:GetServiceCapabilities", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities, "-ns6:GetServiceCapabilities", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetServiceCapabilitiesResponse)
		return soap_closesock(soap);
	ns6__GetServiceCapabilitiesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetServiceCapabilitiesResponse->soap_get(soap, "ns6:GetServiceCapabilitiesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfileInfo(const char *endpoint, const char *soap_action, _ns6__GetAuthenticationProfileInfo *ns6__GetAuthenticationProfileInfo, _ns6__GetAuthenticationProfileInfoResponse *ns6__GetAuthenticationProfileInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetAuthenticationProfileInfo soap_tmp___ns6__GetAuthenticationProfileInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetAuthenticationProfileInfo.ns6__GetAuthenticationProfileInfo = ns6__GetAuthenticationProfileInfo;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetAuthenticationProfileInfo(soap, &soap_tmp___ns6__GetAuthenticationProfileInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetAuthenticationProfileInfo(soap, &soap_tmp___ns6__GetAuthenticationProfileInfo, "-ns6:GetAuthenticationProfileInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetAuthenticationProfileInfo(soap, &soap_tmp___ns6__GetAuthenticationProfileInfo, "-ns6:GetAuthenticationProfileInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetAuthenticationProfileInfoResponse)
		return soap_closesock(soap);
	ns6__GetAuthenticationProfileInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetAuthenticationProfileInfoResponse->soap_get(soap, "ns6:GetAuthenticationProfileInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfileInfoList(const char *endpoint, const char *soap_action, _ns6__GetAuthenticationProfileInfoList *ns6__GetAuthenticationProfileInfoList, _ns6__GetAuthenticationProfileInfoListResponse *ns6__GetAuthenticationProfileInfoListResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetAuthenticationProfileInfoList soap_tmp___ns6__GetAuthenticationProfileInfoList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileInfoList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetAuthenticationProfileInfoList.ns6__GetAuthenticationProfileInfoList = ns6__GetAuthenticationProfileInfoList;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns6__GetAuthenticationProfileInfoList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns6__GetAuthenticationProfileInfoList, "-ns6:GetAuthenticationProfileInfoList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns6__GetAuthenticationProfileInfoList, "-ns6:GetAuthenticationProfileInfoList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetAuthenticationProfileInfoListResponse)
		return soap_closesock(soap);
	ns6__GetAuthenticationProfileInfoListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetAuthenticationProfileInfoListResponse->soap_get(soap, "ns6:GetAuthenticationProfileInfoListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfiles(const char *endpoint, const char *soap_action, _ns6__GetAuthenticationProfiles *ns6__GetAuthenticationProfiles, _ns6__GetAuthenticationProfilesResponse *ns6__GetAuthenticationProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetAuthenticationProfiles soap_tmp___ns6__GetAuthenticationProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfiles";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetAuthenticationProfiles.ns6__GetAuthenticationProfiles = ns6__GetAuthenticationProfiles;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetAuthenticationProfiles(soap, &soap_tmp___ns6__GetAuthenticationProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetAuthenticationProfiles(soap, &soap_tmp___ns6__GetAuthenticationProfiles, "-ns6:GetAuthenticationProfiles", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetAuthenticationProfiles(soap, &soap_tmp___ns6__GetAuthenticationProfiles, "-ns6:GetAuthenticationProfiles", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetAuthenticationProfilesResponse)
		return soap_closesock(soap);
	ns6__GetAuthenticationProfilesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetAuthenticationProfilesResponse->soap_get(soap, "ns6:GetAuthenticationProfilesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetAuthenticationProfileList(const char *endpoint, const char *soap_action, _ns6__GetAuthenticationProfileList *ns6__GetAuthenticationProfileList, _ns6__GetAuthenticationProfileListResponse *ns6__GetAuthenticationProfileListResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetAuthenticationProfileList soap_tmp___ns6__GetAuthenticationProfileList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetAuthenticationProfileList.ns6__GetAuthenticationProfileList = ns6__GetAuthenticationProfileList;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetAuthenticationProfileList(soap, &soap_tmp___ns6__GetAuthenticationProfileList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetAuthenticationProfileList(soap, &soap_tmp___ns6__GetAuthenticationProfileList, "-ns6:GetAuthenticationProfileList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetAuthenticationProfileList(soap, &soap_tmp___ns6__GetAuthenticationProfileList, "-ns6:GetAuthenticationProfileList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetAuthenticationProfileListResponse)
		return soap_closesock(soap);
	ns6__GetAuthenticationProfileListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetAuthenticationProfileListResponse->soap_get(soap, "ns6:GetAuthenticationProfileListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::CreateAuthenticationProfile(const char *endpoint, const char *soap_action, _ns6__CreateAuthenticationProfile *ns6__CreateAuthenticationProfile, _ns6__CreateAuthenticationProfileResponse *ns6__CreateAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns6__CreateAuthenticationProfile soap_tmp___ns6__CreateAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/CreateAuthenticationProfile";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__CreateAuthenticationProfile.ns6__CreateAuthenticationProfile = ns6__CreateAuthenticationProfile;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__CreateAuthenticationProfile(soap, &soap_tmp___ns6__CreateAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__CreateAuthenticationProfile(soap, &soap_tmp___ns6__CreateAuthenticationProfile, "-ns6:CreateAuthenticationProfile", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__CreateAuthenticationProfile(soap, &soap_tmp___ns6__CreateAuthenticationProfile, "-ns6:CreateAuthenticationProfile", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__CreateAuthenticationProfileResponse)
		return soap_closesock(soap);
	ns6__CreateAuthenticationProfileResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__CreateAuthenticationProfileResponse->soap_get(soap, "ns6:CreateAuthenticationProfileResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::SetAuthenticationProfile(const char *endpoint, const char *soap_action, _ns6__SetAuthenticationProfile *ns6__SetAuthenticationProfile, _ns6__SetAuthenticationProfileResponse *ns6__SetAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns6__SetAuthenticationProfile soap_tmp___ns6__SetAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/SetAuthenticationProfile";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__SetAuthenticationProfile.ns6__SetAuthenticationProfile = ns6__SetAuthenticationProfile;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__SetAuthenticationProfile(soap, &soap_tmp___ns6__SetAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__SetAuthenticationProfile(soap, &soap_tmp___ns6__SetAuthenticationProfile, "-ns6:SetAuthenticationProfile", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__SetAuthenticationProfile(soap, &soap_tmp___ns6__SetAuthenticationProfile, "-ns6:SetAuthenticationProfile", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__SetAuthenticationProfileResponse)
		return soap_closesock(soap);
	ns6__SetAuthenticationProfileResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__SetAuthenticationProfileResponse->soap_get(soap, "ns6:SetAuthenticationProfileResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::ModifyAuthenticationProfile(const char *endpoint, const char *soap_action, _ns6__ModifyAuthenticationProfile *ns6__ModifyAuthenticationProfile, _ns6__ModifyAuthenticationProfileResponse *ns6__ModifyAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns6__ModifyAuthenticationProfile soap_tmp___ns6__ModifyAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/ModifyAuthenticationProfile";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__ModifyAuthenticationProfile.ns6__ModifyAuthenticationProfile = ns6__ModifyAuthenticationProfile;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__ModifyAuthenticationProfile(soap, &soap_tmp___ns6__ModifyAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__ModifyAuthenticationProfile(soap, &soap_tmp___ns6__ModifyAuthenticationProfile, "-ns6:ModifyAuthenticationProfile", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__ModifyAuthenticationProfile(soap, &soap_tmp___ns6__ModifyAuthenticationProfile, "-ns6:ModifyAuthenticationProfile", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__ModifyAuthenticationProfileResponse)
		return soap_closesock(soap);
	ns6__ModifyAuthenticationProfileResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__ModifyAuthenticationProfileResponse->soap_get(soap, "ns6:ModifyAuthenticationProfileResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::DeleteAuthenticationProfile(const char *endpoint, const char *soap_action, _ns6__DeleteAuthenticationProfile *ns6__DeleteAuthenticationProfile, _ns6__DeleteAuthenticationProfileResponse *ns6__DeleteAuthenticationProfileResponse)
{	struct soap *soap = this->soap;
	struct __ns6__DeleteAuthenticationProfile soap_tmp___ns6__DeleteAuthenticationProfile;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/DeleteAuthenticationProfile";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__DeleteAuthenticationProfile.ns6__DeleteAuthenticationProfile = ns6__DeleteAuthenticationProfile;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__DeleteAuthenticationProfile(soap, &soap_tmp___ns6__DeleteAuthenticationProfile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__DeleteAuthenticationProfile(soap, &soap_tmp___ns6__DeleteAuthenticationProfile, "-ns6:DeleteAuthenticationProfile", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__DeleteAuthenticationProfile(soap, &soap_tmp___ns6__DeleteAuthenticationProfile, "-ns6:DeleteAuthenticationProfile", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__DeleteAuthenticationProfileResponse)
		return soap_closesock(soap);
	ns6__DeleteAuthenticationProfileResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__DeleteAuthenticationProfileResponse->soap_get(soap, "ns6:DeleteAuthenticationProfileResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevelInfo(const char *endpoint, const char *soap_action, _ns6__GetSecurityLevelInfo *ns6__GetSecurityLevelInfo, _ns6__GetSecurityLevelInfoResponse *ns6__GetSecurityLevelInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetSecurityLevelInfo soap_tmp___ns6__GetSecurityLevelInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetSecurityLevelInfo.ns6__GetSecurityLevelInfo = ns6__GetSecurityLevelInfo;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetSecurityLevelInfo(soap, &soap_tmp___ns6__GetSecurityLevelInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetSecurityLevelInfo(soap, &soap_tmp___ns6__GetSecurityLevelInfo, "-ns6:GetSecurityLevelInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetSecurityLevelInfo(soap, &soap_tmp___ns6__GetSecurityLevelInfo, "-ns6:GetSecurityLevelInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetSecurityLevelInfoResponse)
		return soap_closesock(soap);
	ns6__GetSecurityLevelInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetSecurityLevelInfoResponse->soap_get(soap, "ns6:GetSecurityLevelInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevelInfoList(const char *endpoint, const char *soap_action, _ns6__GetSecurityLevelInfoList *ns6__GetSecurityLevelInfoList, _ns6__GetSecurityLevelInfoListResponse *ns6__GetSecurityLevelInfoListResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetSecurityLevelInfoList soap_tmp___ns6__GetSecurityLevelInfoList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelInfoList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetSecurityLevelInfoList.ns6__GetSecurityLevelInfoList = ns6__GetSecurityLevelInfoList;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetSecurityLevelInfoList(soap, &soap_tmp___ns6__GetSecurityLevelInfoList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetSecurityLevelInfoList(soap, &soap_tmp___ns6__GetSecurityLevelInfoList, "-ns6:GetSecurityLevelInfoList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetSecurityLevelInfoList(soap, &soap_tmp___ns6__GetSecurityLevelInfoList, "-ns6:GetSecurityLevelInfoList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetSecurityLevelInfoListResponse)
		return soap_closesock(soap);
	ns6__GetSecurityLevelInfoListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetSecurityLevelInfoListResponse->soap_get(soap, "ns6:GetSecurityLevelInfoListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevels(const char *endpoint, const char *soap_action, _ns6__GetSecurityLevels *ns6__GetSecurityLevels, _ns6__GetSecurityLevelsResponse *ns6__GetSecurityLevelsResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetSecurityLevels soap_tmp___ns6__GetSecurityLevels;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevels";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetSecurityLevels.ns6__GetSecurityLevels = ns6__GetSecurityLevels;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetSecurityLevels(soap, &soap_tmp___ns6__GetSecurityLevels);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetSecurityLevels(soap, &soap_tmp___ns6__GetSecurityLevels, "-ns6:GetSecurityLevels", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetSecurityLevels(soap, &soap_tmp___ns6__GetSecurityLevels, "-ns6:GetSecurityLevels", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetSecurityLevelsResponse)
		return soap_closesock(soap);
	ns6__GetSecurityLevelsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetSecurityLevelsResponse->soap_get(soap, "ns6:GetSecurityLevelsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::GetSecurityLevelList(const char *endpoint, const char *soap_action, _ns6__GetSecurityLevelList *ns6__GetSecurityLevelList, _ns6__GetSecurityLevelListResponse *ns6__GetSecurityLevelListResponse)
{	struct soap *soap = this->soap;
	struct __ns6__GetSecurityLevelList soap_tmp___ns6__GetSecurityLevelList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GetSecurityLevelList.ns6__GetSecurityLevelList = ns6__GetSecurityLevelList;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetSecurityLevelList(soap, &soap_tmp___ns6__GetSecurityLevelList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetSecurityLevelList(soap, &soap_tmp___ns6__GetSecurityLevelList, "-ns6:GetSecurityLevelList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetSecurityLevelList(soap, &soap_tmp___ns6__GetSecurityLevelList, "-ns6:GetSecurityLevelList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GetSecurityLevelListResponse)
		return soap_closesock(soap);
	ns6__GetSecurityLevelListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetSecurityLevelListResponse->soap_get(soap, "ns6:GetSecurityLevelListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::CreateSecurityLevel(const char *endpoint, const char *soap_action, _ns6__CreateSecurityLevel *ns6__CreateSecurityLevel, _ns6__CreateSecurityLevelResponse *ns6__CreateSecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns6__CreateSecurityLevel soap_tmp___ns6__CreateSecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/CreateSecurityLevel";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__CreateSecurityLevel.ns6__CreateSecurityLevel = ns6__CreateSecurityLevel;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__CreateSecurityLevel(soap, &soap_tmp___ns6__CreateSecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__CreateSecurityLevel(soap, &soap_tmp___ns6__CreateSecurityLevel, "-ns6:CreateSecurityLevel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__CreateSecurityLevel(soap, &soap_tmp___ns6__CreateSecurityLevel, "-ns6:CreateSecurityLevel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__CreateSecurityLevelResponse)
		return soap_closesock(soap);
	ns6__CreateSecurityLevelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__CreateSecurityLevelResponse->soap_get(soap, "ns6:CreateSecurityLevelResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::SetSecurityLevel(const char *endpoint, const char *soap_action, _ns6__SetSecurityLevel *ns6__SetSecurityLevel, _ns6__SetSecurityLevelResponse *ns6__SetSecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns6__SetSecurityLevel soap_tmp___ns6__SetSecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/SetSecurityLevel";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__SetSecurityLevel.ns6__SetSecurityLevel = ns6__SetSecurityLevel;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__SetSecurityLevel(soap, &soap_tmp___ns6__SetSecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__SetSecurityLevel(soap, &soap_tmp___ns6__SetSecurityLevel, "-ns6:SetSecurityLevel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__SetSecurityLevel(soap, &soap_tmp___ns6__SetSecurityLevel, "-ns6:SetSecurityLevel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__SetSecurityLevelResponse)
		return soap_closesock(soap);
	ns6__SetSecurityLevelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__SetSecurityLevelResponse->soap_get(soap, "ns6:SetSecurityLevelResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::ModifySecurityLevel(const char *endpoint, const char *soap_action, _ns6__ModifySecurityLevel *ns6__ModifySecurityLevel, _ns6__ModifySecurityLevelResponse *ns6__ModifySecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns6__ModifySecurityLevel soap_tmp___ns6__ModifySecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/ModifySecurityLevel";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__ModifySecurityLevel.ns6__ModifySecurityLevel = ns6__ModifySecurityLevel;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__ModifySecurityLevel(soap, &soap_tmp___ns6__ModifySecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__ModifySecurityLevel(soap, &soap_tmp___ns6__ModifySecurityLevel, "-ns6:ModifySecurityLevel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__ModifySecurityLevel(soap, &soap_tmp___ns6__ModifySecurityLevel, "-ns6:ModifySecurityLevel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__ModifySecurityLevelResponse)
		return soap_closesock(soap);
	ns6__ModifySecurityLevelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__ModifySecurityLevelResponse->soap_get(soap, "ns6:ModifySecurityLevelResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AuthenticationBehaviorBindingProxy::DeleteSecurityLevel(const char *endpoint, const char *soap_action, _ns6__DeleteSecurityLevel *ns6__DeleteSecurityLevel, _ns6__DeleteSecurityLevelResponse *ns6__DeleteSecurityLevelResponse)
{	struct soap *soap = this->soap;
	struct __ns6__DeleteSecurityLevel soap_tmp___ns6__DeleteSecurityLevel;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/authenticationbehavior/wsdl/DeleteSecurityLevel";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns6__DeleteSecurityLevel.ns6__DeleteSecurityLevel = ns6__DeleteSecurityLevel;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns6__DeleteSecurityLevel(soap, &soap_tmp___ns6__DeleteSecurityLevel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__DeleteSecurityLevel(soap, &soap_tmp___ns6__DeleteSecurityLevel, "-ns6:DeleteSecurityLevel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__DeleteSecurityLevel(soap, &soap_tmp___ns6__DeleteSecurityLevel, "-ns6:DeleteSecurityLevel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__DeleteSecurityLevelResponse)
		return soap_closesock(soap);
	ns6__DeleteSecurityLevelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__DeleteSecurityLevelResponse->soap_get(soap, "ns6:DeleteSecurityLevelResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
