/* soapScheduleBindingProxy.h
   Generated by gSOAP 2.8.17r from onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapScheduleBindingProxy_H
#define soapScheduleBindingProxy_H
#include "soapH.h"

class SOAP_CMAC ScheduleBindingProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'ScheduleBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ScheduleBindingProxy();
	/// Constructor to use/share an engine state
	ScheduleBindingProxy(struct soap*);
	/// Constructor with endpoint URL
	ScheduleBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ScheduleBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ScheduleBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ScheduleBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ScheduleBindingProxy();
	/// Initializer used by constructors
	virtual	void ScheduleBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_ns11__GetServiceCapabilities *ns11__GetServiceCapabilities, _ns11__GetServiceCapabilitiesResponse *ns11__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns11__GetServiceCapabilities, ns11__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns11__GetServiceCapabilities *ns11__GetServiceCapabilities, _ns11__GetServiceCapabilitiesResponse *ns11__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetScheduleState' (returns error code or SOAP_OK)
	virtual	int GetScheduleState(_ns11__GetScheduleState *ns11__GetScheduleState, _ns11__GetScheduleStateResponse *ns11__GetScheduleStateResponse) { return this->GetScheduleState(NULL, NULL, ns11__GetScheduleState, ns11__GetScheduleStateResponse); }
	virtual	int GetScheduleState(const char *endpoint, const char *soap_action, _ns11__GetScheduleState *ns11__GetScheduleState, _ns11__GetScheduleStateResponse *ns11__GetScheduleStateResponse);

	/// Web service operation 'GetScheduleInfo' (returns error code or SOAP_OK)
	virtual	int GetScheduleInfo(_ns11__GetScheduleInfo *ns11__GetScheduleInfo, _ns11__GetScheduleInfoResponse *ns11__GetScheduleInfoResponse) { return this->GetScheduleInfo(NULL, NULL, ns11__GetScheduleInfo, ns11__GetScheduleInfoResponse); }
	virtual	int GetScheduleInfo(const char *endpoint, const char *soap_action, _ns11__GetScheduleInfo *ns11__GetScheduleInfo, _ns11__GetScheduleInfoResponse *ns11__GetScheduleInfoResponse);

	/// Web service operation 'GetScheduleInfoList' (returns error code or SOAP_OK)
	virtual	int GetScheduleInfoList(_ns11__GetScheduleInfoList *ns11__GetScheduleInfoList, _ns11__GetScheduleInfoListResponse *ns11__GetScheduleInfoListResponse) { return this->GetScheduleInfoList(NULL, NULL, ns11__GetScheduleInfoList, ns11__GetScheduleInfoListResponse); }
	virtual	int GetScheduleInfoList(const char *endpoint, const char *soap_action, _ns11__GetScheduleInfoList *ns11__GetScheduleInfoList, _ns11__GetScheduleInfoListResponse *ns11__GetScheduleInfoListResponse);

	/// Web service operation 'GetSchedules' (returns error code or SOAP_OK)
	virtual	int GetSchedules(_ns11__GetSchedules *ns11__GetSchedules, _ns11__GetSchedulesResponse *ns11__GetSchedulesResponse) { return this->GetSchedules(NULL, NULL, ns11__GetSchedules, ns11__GetSchedulesResponse); }
	virtual	int GetSchedules(const char *endpoint, const char *soap_action, _ns11__GetSchedules *ns11__GetSchedules, _ns11__GetSchedulesResponse *ns11__GetSchedulesResponse);

	/// Web service operation 'GetScheduleList' (returns error code or SOAP_OK)
	virtual	int GetScheduleList(_ns11__GetScheduleList *ns11__GetScheduleList, _ns11__GetScheduleListResponse *ns11__GetScheduleListResponse) { return this->GetScheduleList(NULL, NULL, ns11__GetScheduleList, ns11__GetScheduleListResponse); }
	virtual	int GetScheduleList(const char *endpoint, const char *soap_action, _ns11__GetScheduleList *ns11__GetScheduleList, _ns11__GetScheduleListResponse *ns11__GetScheduleListResponse);

	/// Web service operation 'CreateSchedule' (returns error code or SOAP_OK)
	virtual	int CreateSchedule(_ns11__CreateSchedule *ns11__CreateSchedule, _ns11__CreateScheduleResponse *ns11__CreateScheduleResponse) { return this->CreateSchedule(NULL, NULL, ns11__CreateSchedule, ns11__CreateScheduleResponse); }
	virtual	int CreateSchedule(const char *endpoint, const char *soap_action, _ns11__CreateSchedule *ns11__CreateSchedule, _ns11__CreateScheduleResponse *ns11__CreateScheduleResponse);

	/// Web service operation 'SetSchedule' (returns error code or SOAP_OK)
	virtual	int SetSchedule(_ns11__SetSchedule *ns11__SetSchedule, _ns11__SetScheduleResponse *ns11__SetScheduleResponse) { return this->SetSchedule(NULL, NULL, ns11__SetSchedule, ns11__SetScheduleResponse); }
	virtual	int SetSchedule(const char *endpoint, const char *soap_action, _ns11__SetSchedule *ns11__SetSchedule, _ns11__SetScheduleResponse *ns11__SetScheduleResponse);

	/// Web service operation 'ModifySchedule' (returns error code or SOAP_OK)
	virtual	int ModifySchedule(_ns11__ModifySchedule *ns11__ModifySchedule, _ns11__ModifyScheduleResponse *ns11__ModifyScheduleResponse) { return this->ModifySchedule(NULL, NULL, ns11__ModifySchedule, ns11__ModifyScheduleResponse); }
	virtual	int ModifySchedule(const char *endpoint, const char *soap_action, _ns11__ModifySchedule *ns11__ModifySchedule, _ns11__ModifyScheduleResponse *ns11__ModifyScheduleResponse);

	/// Web service operation 'DeleteSchedule' (returns error code or SOAP_OK)
	virtual	int DeleteSchedule(_ns11__DeleteSchedule *ns11__DeleteSchedule, _ns11__DeleteScheduleResponse *ns11__DeleteScheduleResponse) { return this->DeleteSchedule(NULL, NULL, ns11__DeleteSchedule, ns11__DeleteScheduleResponse); }
	virtual	int DeleteSchedule(const char *endpoint, const char *soap_action, _ns11__DeleteSchedule *ns11__DeleteSchedule, _ns11__DeleteScheduleResponse *ns11__DeleteScheduleResponse);

	/// Web service operation 'GetSpecialDayGroupInfo' (returns error code or SOAP_OK)
	virtual	int GetSpecialDayGroupInfo(_ns11__GetSpecialDayGroupInfo *ns11__GetSpecialDayGroupInfo, _ns11__GetSpecialDayGroupInfoResponse *ns11__GetSpecialDayGroupInfoResponse) { return this->GetSpecialDayGroupInfo(NULL, NULL, ns11__GetSpecialDayGroupInfo, ns11__GetSpecialDayGroupInfoResponse); }
	virtual	int GetSpecialDayGroupInfo(const char *endpoint, const char *soap_action, _ns11__GetSpecialDayGroupInfo *ns11__GetSpecialDayGroupInfo, _ns11__GetSpecialDayGroupInfoResponse *ns11__GetSpecialDayGroupInfoResponse);

	/// Web service operation 'GetSpecialDayGroupInfoList' (returns error code or SOAP_OK)
	virtual	int GetSpecialDayGroupInfoList(_ns11__GetSpecialDayGroupInfoList *ns11__GetSpecialDayGroupInfoList, _ns11__GetSpecialDayGroupInfoListResponse *ns11__GetSpecialDayGroupInfoListResponse) { return this->GetSpecialDayGroupInfoList(NULL, NULL, ns11__GetSpecialDayGroupInfoList, ns11__GetSpecialDayGroupInfoListResponse); }
	virtual	int GetSpecialDayGroupInfoList(const char *endpoint, const char *soap_action, _ns11__GetSpecialDayGroupInfoList *ns11__GetSpecialDayGroupInfoList, _ns11__GetSpecialDayGroupInfoListResponse *ns11__GetSpecialDayGroupInfoListResponse);

	/// Web service operation 'GetSpecialDayGroups' (returns error code or SOAP_OK)
	virtual	int GetSpecialDayGroups(_ns11__GetSpecialDayGroups *ns11__GetSpecialDayGroups, _ns11__GetSpecialDayGroupsResponse *ns11__GetSpecialDayGroupsResponse) { return this->GetSpecialDayGroups(NULL, NULL, ns11__GetSpecialDayGroups, ns11__GetSpecialDayGroupsResponse); }
	virtual	int GetSpecialDayGroups(const char *endpoint, const char *soap_action, _ns11__GetSpecialDayGroups *ns11__GetSpecialDayGroups, _ns11__GetSpecialDayGroupsResponse *ns11__GetSpecialDayGroupsResponse);

	/// Web service operation 'GetSpecialDayGroupList' (returns error code or SOAP_OK)
	virtual	int GetSpecialDayGroupList(_ns11__GetSpecialDayGroupList *ns11__GetSpecialDayGroupList, _ns11__GetSpecialDayGroupListResponse *ns11__GetSpecialDayGroupListResponse) { return this->GetSpecialDayGroupList(NULL, NULL, ns11__GetSpecialDayGroupList, ns11__GetSpecialDayGroupListResponse); }
	virtual	int GetSpecialDayGroupList(const char *endpoint, const char *soap_action, _ns11__GetSpecialDayGroupList *ns11__GetSpecialDayGroupList, _ns11__GetSpecialDayGroupListResponse *ns11__GetSpecialDayGroupListResponse);

	/// Web service operation 'CreateSpecialDayGroup' (returns error code or SOAP_OK)
	virtual	int CreateSpecialDayGroup(_ns11__CreateSpecialDayGroup *ns11__CreateSpecialDayGroup, _ns11__CreateSpecialDayGroupResponse *ns11__CreateSpecialDayGroupResponse) { return this->CreateSpecialDayGroup(NULL, NULL, ns11__CreateSpecialDayGroup, ns11__CreateSpecialDayGroupResponse); }
	virtual	int CreateSpecialDayGroup(const char *endpoint, const char *soap_action, _ns11__CreateSpecialDayGroup *ns11__CreateSpecialDayGroup, _ns11__CreateSpecialDayGroupResponse *ns11__CreateSpecialDayGroupResponse);

	/// Web service operation 'SetSpecialDayGroup' (returns error code or SOAP_OK)
	virtual	int SetSpecialDayGroup(_ns11__SetSpecialDayGroup *ns11__SetSpecialDayGroup, _ns11__SetSpecialDayGroupResponse *ns11__SetSpecialDayGroupResponse) { return this->SetSpecialDayGroup(NULL, NULL, ns11__SetSpecialDayGroup, ns11__SetSpecialDayGroupResponse); }
	virtual	int SetSpecialDayGroup(const char *endpoint, const char *soap_action, _ns11__SetSpecialDayGroup *ns11__SetSpecialDayGroup, _ns11__SetSpecialDayGroupResponse *ns11__SetSpecialDayGroupResponse);

	/// Web service operation 'ModifySpecialDayGroup' (returns error code or SOAP_OK)
	virtual	int ModifySpecialDayGroup(_ns11__ModifySpecialDayGroup *ns11__ModifySpecialDayGroup, _ns11__ModifySpecialDayGroupResponse *ns11__ModifySpecialDayGroupResponse) { return this->ModifySpecialDayGroup(NULL, NULL, ns11__ModifySpecialDayGroup, ns11__ModifySpecialDayGroupResponse); }
	virtual	int ModifySpecialDayGroup(const char *endpoint, const char *soap_action, _ns11__ModifySpecialDayGroup *ns11__ModifySpecialDayGroup, _ns11__ModifySpecialDayGroupResponse *ns11__ModifySpecialDayGroupResponse);

	/// Web service operation 'DeleteSpecialDayGroup' (returns error code or SOAP_OK)
	virtual	int DeleteSpecialDayGroup(_ns11__DeleteSpecialDayGroup *ns11__DeleteSpecialDayGroup, _ns11__DeleteSpecialDayGroupResponse *ns11__DeleteSpecialDayGroupResponse) { return this->DeleteSpecialDayGroup(NULL, NULL, ns11__DeleteSpecialDayGroup, ns11__DeleteSpecialDayGroupResponse); }
	virtual	int DeleteSpecialDayGroup(const char *endpoint, const char *soap_action, _ns11__DeleteSpecialDayGroup *ns11__DeleteSpecialDayGroup, _ns11__DeleteSpecialDayGroupResponse *ns11__DeleteSpecialDayGroupResponse);
};
#endif
