/* soapCredentialBindingProxy.cpp
   Generated by gSOAP 2.8.17r from onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapCredentialBindingProxy.h"

CredentialBindingProxy::CredentialBindingProxy()
{	this->soap = soap_new();
	this->own = true;
	CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

CredentialBindingProxy::CredentialBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	CredentialBindingProxy_init(_soap->imode, _soap->omode);
}

CredentialBindingProxy::CredentialBindingProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

CredentialBindingProxy::CredentialBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	CredentialBindingProxy_init(iomode, iomode);
}

CredentialBindingProxy::CredentialBindingProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	CredentialBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

CredentialBindingProxy::CredentialBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	CredentialBindingProxy_init(imode, omode);
}

CredentialBindingProxy::~CredentialBindingProxy()
{	if (this->own)
		soap_free(this->soap);
}

void CredentialBindingProxy::CredentialBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
	{"wsc", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns2", "http://www.onvif.org/ver10/pacs", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"name", "http://www.onvif.org/ver10/advancedsecurity/wsdl/AdvancedSecurityServiceBinding", NULL, NULL},
	{"name10", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
	{"name11", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
	{"name12", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
	{"name13", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
	{"name14", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"name2", "http://www.onvif.org/ver10/advancedsecurity/wsdl/KeystoreBinding", NULL, NULL},
	{"name3", "http://www.onvif.org/ver10/advancedsecurity/wsdl/TLSServerBinding", NULL, NULL},
	{"name4", "http://www.onvif.org/ver10/advancedsecurity/wsdl/Dot1XBinding", NULL, NULL},
	{"ns5", "http://www.onvif.org/ver10/advancedsecurity/wsdl", NULL, NULL},
	{"name5", "http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding", NULL, NULL},
	{"name6", "http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"name7", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
	{"name8", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"name9", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
	{"ns1", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
	{"ns10", "http://www.onvif.org/ver10/provisioning/wsdl", NULL, NULL},
	{"ns11", "http://www.onvif.org/ver10/schedule/wsdl", NULL, NULL},
	{"ns12", "http://www.onvif.org/ver10/thermal/wsdl", NULL, NULL},
	{"ns3", "http://www.onvif.org/ver10/accessrules/wsdl", NULL, NULL},
	{"ns4", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
	{"ns6", "http://www.onvif.org/ver10/authenticationbehavior/wsdl", NULL, NULL},
	{"ns7", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
	{"ns8", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
	{"ns9", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
	{"tad", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
	{"tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
	{"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
	{"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void CredentialBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void CredentialBindingProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void CredentialBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void CredentialBindingProxy::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
	this->soap->header->wsse__Security = wsse__Security;
}

const SOAP_ENV__Header *CredentialBindingProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *CredentialBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *CredentialBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *CredentialBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int CredentialBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int CredentialBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void CredentialBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void CredentialBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *CredentialBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int CredentialBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns7__GetServiceCapabilities *ns7__GetServiceCapabilities, _ns7__GetServiceCapabilitiesResponse *ns7__GetServiceCapabilitiesResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetServiceCapabilities soap_tmp___ns7__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetServiceCapabilities";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetServiceCapabilities.ns7__GetServiceCapabilities = ns7__GetServiceCapabilities;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetServiceCapabilities(soap, &soap_tmp___ns7__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetServiceCapabilities(soap, &soap_tmp___ns7__GetServiceCapabilities, "-ns7:GetServiceCapabilities", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetServiceCapabilities(soap, &soap_tmp___ns7__GetServiceCapabilities, "-ns7:GetServiceCapabilities", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetServiceCapabilitiesResponse)
		return soap_closesock(soap);
	ns7__GetServiceCapabilitiesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetServiceCapabilitiesResponse->soap_get(soap, "ns7:GetServiceCapabilitiesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetSupportedFormatTypes(const char *endpoint, const char *soap_action, _ns7__GetSupportedFormatTypes *ns7__GetSupportedFormatTypes, _ns7__GetSupportedFormatTypesResponse *ns7__GetSupportedFormatTypesResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetSupportedFormatTypes soap_tmp___ns7__GetSupportedFormatTypes;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetSupportedFormatTypes";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetSupportedFormatTypes.ns7__GetSupportedFormatTypes = ns7__GetSupportedFormatTypes;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetSupportedFormatTypes(soap, &soap_tmp___ns7__GetSupportedFormatTypes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetSupportedFormatTypes(soap, &soap_tmp___ns7__GetSupportedFormatTypes, "-ns7:GetSupportedFormatTypes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetSupportedFormatTypes(soap, &soap_tmp___ns7__GetSupportedFormatTypes, "-ns7:GetSupportedFormatTypes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetSupportedFormatTypesResponse)
		return soap_closesock(soap);
	ns7__GetSupportedFormatTypesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetSupportedFormatTypesResponse->soap_get(soap, "ns7:GetSupportedFormatTypesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialInfo(const char *endpoint, const char *soap_action, _ns7__GetCredentialInfo *ns7__GetCredentialInfo, _ns7__GetCredentialInfoResponse *ns7__GetCredentialInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetCredentialInfo soap_tmp___ns7__GetCredentialInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetCredentialInfo.ns7__GetCredentialInfo = ns7__GetCredentialInfo;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetCredentialInfo(soap, &soap_tmp___ns7__GetCredentialInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetCredentialInfo(soap, &soap_tmp___ns7__GetCredentialInfo, "-ns7:GetCredentialInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetCredentialInfo(soap, &soap_tmp___ns7__GetCredentialInfo, "-ns7:GetCredentialInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetCredentialInfoResponse)
		return soap_closesock(soap);
	ns7__GetCredentialInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetCredentialInfoResponse->soap_get(soap, "ns7:GetCredentialInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialInfoList(const char *endpoint, const char *soap_action, _ns7__GetCredentialInfoList *ns7__GetCredentialInfoList, _ns7__GetCredentialInfoListResponse *ns7__GetCredentialInfoListResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetCredentialInfoList soap_tmp___ns7__GetCredentialInfoList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfoList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetCredentialInfoList.ns7__GetCredentialInfoList = ns7__GetCredentialInfoList;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetCredentialInfoList(soap, &soap_tmp___ns7__GetCredentialInfoList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetCredentialInfoList(soap, &soap_tmp___ns7__GetCredentialInfoList, "-ns7:GetCredentialInfoList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetCredentialInfoList(soap, &soap_tmp___ns7__GetCredentialInfoList, "-ns7:GetCredentialInfoList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetCredentialInfoListResponse)
		return soap_closesock(soap);
	ns7__GetCredentialInfoListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetCredentialInfoListResponse->soap_get(soap, "ns7:GetCredentialInfoListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentials(const char *endpoint, const char *soap_action, _ns7__GetCredentials *ns7__GetCredentials, _ns7__GetCredentialsResponse *ns7__GetCredentialsResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetCredentials soap_tmp___ns7__GetCredentials;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentials";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetCredentials.ns7__GetCredentials = ns7__GetCredentials;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetCredentials(soap, &soap_tmp___ns7__GetCredentials);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetCredentials(soap, &soap_tmp___ns7__GetCredentials, "-ns7:GetCredentials", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetCredentials(soap, &soap_tmp___ns7__GetCredentials, "-ns7:GetCredentials", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetCredentialsResponse)
		return soap_closesock(soap);
	ns7__GetCredentialsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetCredentialsResponse->soap_get(soap, "ns7:GetCredentialsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialList(const char *endpoint, const char *soap_action, _ns7__GetCredentialList *ns7__GetCredentialList, _ns7__GetCredentialListResponse *ns7__GetCredentialListResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetCredentialList soap_tmp___ns7__GetCredentialList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetCredentialList.ns7__GetCredentialList = ns7__GetCredentialList;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetCredentialList(soap, &soap_tmp___ns7__GetCredentialList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetCredentialList(soap, &soap_tmp___ns7__GetCredentialList, "-ns7:GetCredentialList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetCredentialList(soap, &soap_tmp___ns7__GetCredentialList, "-ns7:GetCredentialList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetCredentialListResponse)
		return soap_closesock(soap);
	ns7__GetCredentialListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetCredentialListResponse->soap_get(soap, "ns7:GetCredentialListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::CreateCredential(const char *endpoint, const char *soap_action, _ns7__CreateCredential *ns7__CreateCredential, _ns7__CreateCredentialResponse *ns7__CreateCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns7__CreateCredential soap_tmp___ns7__CreateCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/CreateCredential";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__CreateCredential.ns7__CreateCredential = ns7__CreateCredential;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__CreateCredential(soap, &soap_tmp___ns7__CreateCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__CreateCredential(soap, &soap_tmp___ns7__CreateCredential, "-ns7:CreateCredential", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__CreateCredential(soap, &soap_tmp___ns7__CreateCredential, "-ns7:CreateCredential", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__CreateCredentialResponse)
		return soap_closesock(soap);
	ns7__CreateCredentialResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__CreateCredentialResponse->soap_get(soap, "ns7:CreateCredentialResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredential(const char *endpoint, const char *soap_action, _ns7__SetCredential *ns7__SetCredential, _ns7__SetCredentialResponse *ns7__SetCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns7__SetCredential soap_tmp___ns7__SetCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredential";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__SetCredential.ns7__SetCredential = ns7__SetCredential;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__SetCredential(soap, &soap_tmp___ns7__SetCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__SetCredential(soap, &soap_tmp___ns7__SetCredential, "-ns7:SetCredential", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__SetCredential(soap, &soap_tmp___ns7__SetCredential, "-ns7:SetCredential", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__SetCredentialResponse)
		return soap_closesock(soap);
	ns7__SetCredentialResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__SetCredentialResponse->soap_get(soap, "ns7:SetCredentialResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::ModifyCredential(const char *endpoint, const char *soap_action, _ns7__ModifyCredential *ns7__ModifyCredential, _ns7__ModifyCredentialResponse *ns7__ModifyCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns7__ModifyCredential soap_tmp___ns7__ModifyCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/ModifyCredential";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__ModifyCredential.ns7__ModifyCredential = ns7__ModifyCredential;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__ModifyCredential(soap, &soap_tmp___ns7__ModifyCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__ModifyCredential(soap, &soap_tmp___ns7__ModifyCredential, "-ns7:ModifyCredential", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__ModifyCredential(soap, &soap_tmp___ns7__ModifyCredential, "-ns7:ModifyCredential", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__ModifyCredentialResponse)
		return soap_closesock(soap);
	ns7__ModifyCredentialResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__ModifyCredentialResponse->soap_get(soap, "ns7:ModifyCredentialResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredential(const char *endpoint, const char *soap_action, _ns7__DeleteCredential *ns7__DeleteCredential, _ns7__DeleteCredentialResponse *ns7__DeleteCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns7__DeleteCredential soap_tmp___ns7__DeleteCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredential";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__DeleteCredential.ns7__DeleteCredential = ns7__DeleteCredential;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__DeleteCredential(soap, &soap_tmp___ns7__DeleteCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__DeleteCredential(soap, &soap_tmp___ns7__DeleteCredential, "-ns7:DeleteCredential", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__DeleteCredential(soap, &soap_tmp___ns7__DeleteCredential, "-ns7:DeleteCredential", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__DeleteCredentialResponse)
		return soap_closesock(soap);
	ns7__DeleteCredentialResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__DeleteCredentialResponse->soap_get(soap, "ns7:DeleteCredentialResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialState(const char *endpoint, const char *soap_action, _ns7__GetCredentialState *ns7__GetCredentialState, _ns7__GetCredentialStateResponse *ns7__GetCredentialStateResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetCredentialState soap_tmp___ns7__GetCredentialState;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialState";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetCredentialState.ns7__GetCredentialState = ns7__GetCredentialState;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetCredentialState(soap, &soap_tmp___ns7__GetCredentialState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetCredentialState(soap, &soap_tmp___ns7__GetCredentialState, "-ns7:GetCredentialState", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetCredentialState(soap, &soap_tmp___ns7__GetCredentialState, "-ns7:GetCredentialState", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetCredentialStateResponse)
		return soap_closesock(soap);
	ns7__GetCredentialStateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetCredentialStateResponse->soap_get(soap, "ns7:GetCredentialStateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::EnableCredential(const char *endpoint, const char *soap_action, _ns7__EnableCredential *ns7__EnableCredential, _ns7__EnableCredentialResponse *ns7__EnableCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns7__EnableCredential soap_tmp___ns7__EnableCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/EnableCredential";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__EnableCredential.ns7__EnableCredential = ns7__EnableCredential;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__EnableCredential(soap, &soap_tmp___ns7__EnableCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__EnableCredential(soap, &soap_tmp___ns7__EnableCredential, "-ns7:EnableCredential", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__EnableCredential(soap, &soap_tmp___ns7__EnableCredential, "-ns7:EnableCredential", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__EnableCredentialResponse)
		return soap_closesock(soap);
	ns7__EnableCredentialResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__EnableCredentialResponse->soap_get(soap, "ns7:EnableCredentialResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DisableCredential(const char *endpoint, const char *soap_action, _ns7__DisableCredential *ns7__DisableCredential, _ns7__DisableCredentialResponse *ns7__DisableCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns7__DisableCredential soap_tmp___ns7__DisableCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DisableCredential";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__DisableCredential.ns7__DisableCredential = ns7__DisableCredential;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__DisableCredential(soap, &soap_tmp___ns7__DisableCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__DisableCredential(soap, &soap_tmp___ns7__DisableCredential, "-ns7:DisableCredential", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__DisableCredential(soap, &soap_tmp___ns7__DisableCredential, "-ns7:DisableCredential", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__DisableCredentialResponse)
		return soap_closesock(soap);
	ns7__DisableCredentialResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__DisableCredentialResponse->soap_get(soap, "ns7:DisableCredentialResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::ResetAntipassbackViolation(const char *endpoint, const char *soap_action, _ns7__ResetAntipassbackViolation *ns7__ResetAntipassbackViolation, _ns7__ResetAntipassbackViolationResponse *ns7__ResetAntipassbackViolationResponse)
{	struct soap *soap = this->soap;
	struct __ns7__ResetAntipassbackViolation soap_tmp___ns7__ResetAntipassbackViolation;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/ResetAntipassbackViolation";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__ResetAntipassbackViolation.ns7__ResetAntipassbackViolation = ns7__ResetAntipassbackViolation;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__ResetAntipassbackViolation(soap, &soap_tmp___ns7__ResetAntipassbackViolation);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__ResetAntipassbackViolation(soap, &soap_tmp___ns7__ResetAntipassbackViolation, "-ns7:ResetAntipassbackViolation", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__ResetAntipassbackViolation(soap, &soap_tmp___ns7__ResetAntipassbackViolation, "-ns7:ResetAntipassbackViolation", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__ResetAntipassbackViolationResponse)
		return soap_closesock(soap);
	ns7__ResetAntipassbackViolationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__ResetAntipassbackViolationResponse->soap_get(soap, "ns7:ResetAntipassbackViolationResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialIdentifiers(const char *endpoint, const char *soap_action, _ns7__GetCredentialIdentifiers *ns7__GetCredentialIdentifiers, _ns7__GetCredentialIdentifiersResponse *ns7__GetCredentialIdentifiersResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetCredentialIdentifiers soap_tmp___ns7__GetCredentialIdentifiers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialIdentifiers";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetCredentialIdentifiers.ns7__GetCredentialIdentifiers = ns7__GetCredentialIdentifiers;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetCredentialIdentifiers(soap, &soap_tmp___ns7__GetCredentialIdentifiers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetCredentialIdentifiers(soap, &soap_tmp___ns7__GetCredentialIdentifiers, "-ns7:GetCredentialIdentifiers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetCredentialIdentifiers(soap, &soap_tmp___ns7__GetCredentialIdentifiers, "-ns7:GetCredentialIdentifiers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetCredentialIdentifiersResponse)
		return soap_closesock(soap);
	ns7__GetCredentialIdentifiersResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetCredentialIdentifiersResponse->soap_get(soap, "ns7:GetCredentialIdentifiersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredentialIdentifier(const char *endpoint, const char *soap_action, _ns7__SetCredentialIdentifier *ns7__SetCredentialIdentifier, _ns7__SetCredentialIdentifierResponse *ns7__SetCredentialIdentifierResponse)
{	struct soap *soap = this->soap;
	struct __ns7__SetCredentialIdentifier soap_tmp___ns7__SetCredentialIdentifier;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredentialIdentifier";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__SetCredentialIdentifier.ns7__SetCredentialIdentifier = ns7__SetCredentialIdentifier;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__SetCredentialIdentifier(soap, &soap_tmp___ns7__SetCredentialIdentifier);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__SetCredentialIdentifier(soap, &soap_tmp___ns7__SetCredentialIdentifier, "-ns7:SetCredentialIdentifier", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__SetCredentialIdentifier(soap, &soap_tmp___ns7__SetCredentialIdentifier, "-ns7:SetCredentialIdentifier", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__SetCredentialIdentifierResponse)
		return soap_closesock(soap);
	ns7__SetCredentialIdentifierResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__SetCredentialIdentifierResponse->soap_get(soap, "ns7:SetCredentialIdentifierResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredentialIdentifier(const char *endpoint, const char *soap_action, _ns7__DeleteCredentialIdentifier *ns7__DeleteCredentialIdentifier, _ns7__DeleteCredentialIdentifierResponse *ns7__DeleteCredentialIdentifierResponse)
{	struct soap *soap = this->soap;
	struct __ns7__DeleteCredentialIdentifier soap_tmp___ns7__DeleteCredentialIdentifier;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialIdentifier";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__DeleteCredentialIdentifier.ns7__DeleteCredentialIdentifier = ns7__DeleteCredentialIdentifier;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__DeleteCredentialIdentifier(soap, &soap_tmp___ns7__DeleteCredentialIdentifier);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__DeleteCredentialIdentifier(soap, &soap_tmp___ns7__DeleteCredentialIdentifier, "-ns7:DeleteCredentialIdentifier", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__DeleteCredentialIdentifier(soap, &soap_tmp___ns7__DeleteCredentialIdentifier, "-ns7:DeleteCredentialIdentifier", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__DeleteCredentialIdentifierResponse)
		return soap_closesock(soap);
	ns7__DeleteCredentialIdentifierResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__DeleteCredentialIdentifierResponse->soap_get(soap, "ns7:DeleteCredentialIdentifierResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialAccessProfiles(const char *endpoint, const char *soap_action, _ns7__GetCredentialAccessProfiles *ns7__GetCredentialAccessProfiles, _ns7__GetCredentialAccessProfilesResponse *ns7__GetCredentialAccessProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns7__GetCredentialAccessProfiles soap_tmp___ns7__GetCredentialAccessProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialAccessProfiles";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__GetCredentialAccessProfiles.ns7__GetCredentialAccessProfiles = ns7__GetCredentialAccessProfiles;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__GetCredentialAccessProfiles(soap, &soap_tmp___ns7__GetCredentialAccessProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__GetCredentialAccessProfiles(soap, &soap_tmp___ns7__GetCredentialAccessProfiles, "-ns7:GetCredentialAccessProfiles", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__GetCredentialAccessProfiles(soap, &soap_tmp___ns7__GetCredentialAccessProfiles, "-ns7:GetCredentialAccessProfiles", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__GetCredentialAccessProfilesResponse)
		return soap_closesock(soap);
	ns7__GetCredentialAccessProfilesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__GetCredentialAccessProfilesResponse->soap_get(soap, "ns7:GetCredentialAccessProfilesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredentialAccessProfiles(const char *endpoint, const char *soap_action, _ns7__SetCredentialAccessProfiles *ns7__SetCredentialAccessProfiles, _ns7__SetCredentialAccessProfilesResponse *ns7__SetCredentialAccessProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns7__SetCredentialAccessProfiles soap_tmp___ns7__SetCredentialAccessProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredentialAccessProfiles";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__SetCredentialAccessProfiles.ns7__SetCredentialAccessProfiles = ns7__SetCredentialAccessProfiles;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__SetCredentialAccessProfiles(soap, &soap_tmp___ns7__SetCredentialAccessProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__SetCredentialAccessProfiles(soap, &soap_tmp___ns7__SetCredentialAccessProfiles, "-ns7:SetCredentialAccessProfiles", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__SetCredentialAccessProfiles(soap, &soap_tmp___ns7__SetCredentialAccessProfiles, "-ns7:SetCredentialAccessProfiles", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__SetCredentialAccessProfilesResponse)
		return soap_closesock(soap);
	ns7__SetCredentialAccessProfilesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__SetCredentialAccessProfilesResponse->soap_get(soap, "ns7:SetCredentialAccessProfilesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredentialAccessProfiles(const char *endpoint, const char *soap_action, _ns7__DeleteCredentialAccessProfiles *ns7__DeleteCredentialAccessProfiles, _ns7__DeleteCredentialAccessProfilesResponse *ns7__DeleteCredentialAccessProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns7__DeleteCredentialAccessProfiles soap_tmp___ns7__DeleteCredentialAccessProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialAccessProfiles";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns7__DeleteCredentialAccessProfiles.ns7__DeleteCredentialAccessProfiles = ns7__DeleteCredentialAccessProfiles;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns7__DeleteCredentialAccessProfiles(soap, &soap_tmp___ns7__DeleteCredentialAccessProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns7__DeleteCredentialAccessProfiles(soap, &soap_tmp___ns7__DeleteCredentialAccessProfiles, "-ns7:DeleteCredentialAccessProfiles", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns7__DeleteCredentialAccessProfiles(soap, &soap_tmp___ns7__DeleteCredentialAccessProfiles, "-ns7:DeleteCredentialAccessProfiles", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns7__DeleteCredentialAccessProfilesResponse)
		return soap_closesock(soap);
	ns7__DeleteCredentialAccessProfilesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns7__DeleteCredentialAccessProfilesResponse->soap_get(soap, "ns7:DeleteCredentialAccessProfilesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
