/* soapAuthenticationBehaviorBindingService.cpp
   Generated by gSOAP 2.8.17r from onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapAuthenticationBehaviorBindingService.h"

AuthenticationBehaviorBindingService::AuthenticationBehaviorBindingService()
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

AuthenticationBehaviorBindingService::AuthenticationBehaviorBindingService(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	AuthenticationBehaviorBindingService_init(_soap->imode, _soap->omode);
}

AuthenticationBehaviorBindingService::AuthenticationBehaviorBindingService(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingService_init(iomode, iomode);
}

AuthenticationBehaviorBindingService::AuthenticationBehaviorBindingService(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	AuthenticationBehaviorBindingService_init(imode, omode);
}

AuthenticationBehaviorBindingService::~AuthenticationBehaviorBindingService()
{	if (this->own)
		soap_free(this->soap);
}

void AuthenticationBehaviorBindingService::AuthenticationBehaviorBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
	{"wsc", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
	{"ns2", "http://www.onvif.org/ver10/pacs", NULL, NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
	{"name", "http://www.onvif.org/ver10/advancedsecurity/wsdl/AdvancedSecurityServiceBinding", NULL, NULL},
	{"name10", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL},
	{"name11", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL},
	{"name12", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL},
	{"name13", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL},
	{"name14", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"name2", "http://www.onvif.org/ver10/advancedsecurity/wsdl/KeystoreBinding", NULL, NULL},
	{"name3", "http://www.onvif.org/ver10/advancedsecurity/wsdl/TLSServerBinding", NULL, NULL},
	{"name4", "http://www.onvif.org/ver10/advancedsecurity/wsdl/Dot1XBinding", NULL, NULL},
	{"ns5", "http://www.onvif.org/ver10/advancedsecurity/wsdl", NULL, NULL},
	{"name5", "http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding", NULL, NULL},
	{"name6", "http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding", NULL, NULL},
	{"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
	{"name7", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL},
	{"name8", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL},
	{"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
	{"name9", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL},
	{"ns1", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
	{"ns10", "http://www.onvif.org/ver10/provisioning/wsdl", NULL, NULL},
	{"ns11", "http://www.onvif.org/ver10/schedule/wsdl", NULL, NULL},
	{"ns12", "http://www.onvif.org/ver10/thermal/wsdl", NULL, NULL},
	{"ns3", "http://www.onvif.org/ver10/accessrules/wsdl", NULL, NULL},
	{"ns4", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
	{"ns6", "http://www.onvif.org/ver10/authenticationbehavior/wsdl", NULL, NULL},
	{"ns7", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
	{"ns8", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
	{"ns9", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
	{"tad", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL},
	{"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
	{"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
	{"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
	{"tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
	{"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
	{"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
	{"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
	{"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
	{"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void AuthenticationBehaviorBindingService::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void AuthenticationBehaviorBindingService::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	AuthenticationBehaviorBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
AuthenticationBehaviorBindingService *AuthenticationBehaviorBindingService::copy()
{	AuthenticationBehaviorBindingService *dup = SOAP_NEW_COPY(AuthenticationBehaviorBindingService);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

int AuthenticationBehaviorBindingService::soap_close_socket()
{	return soap_closesock(this->soap);
}

int AuthenticationBehaviorBindingService::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

int AuthenticationBehaviorBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this->soap, string, detailXML);
}

int AuthenticationBehaviorBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

int AuthenticationBehaviorBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this->soap, string, detailXML);
}

int AuthenticationBehaviorBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

void AuthenticationBehaviorBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void AuthenticationBehaviorBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *AuthenticationBehaviorBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

void AuthenticationBehaviorBindingService::soap_noheader()
{	this->soap->header = NULL;
}

void AuthenticationBehaviorBindingService::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct _wsse__Security *wsse__Security)
{	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
	this->soap->header->wsse__Security = wsse__Security;
}

const SOAP_ENV__Header *AuthenticationBehaviorBindingService::soap_header()
{	return this->soap->header;
}

int AuthenticationBehaviorBindingService::run(int port)
{	if (soap_valid_socket(this->soap->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				return this->soap->error;
			soap_destroy(this->soap);
			soap_end(this->soap);
		}
	}
	else
		return this->soap->error;
	return SOAP_OK;
}

SOAP_SOCKET AuthenticationBehaviorBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this->soap, host, port, backlog);
}

SOAP_SOCKET AuthenticationBehaviorBindingService::accept()
{	return soap_accept(this->soap);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int AuthenticationBehaviorBindingService::ssl_accept()
{	return soap_ssl_accept(this->soap);
}
#endif

int AuthenticationBehaviorBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->soap->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->soap->max_keep_alive > 0 && !--k)
			this->soap->keep_alive = 0;
#endif

		if (soap_begin_serve(this->soap))
		{	if (this->soap->error >= SOAP_STOP)
				continue;
			return this->soap->error;
		}
		if (dispatch() || (this->soap->fserveloop && this->soap->fserveloop(this->soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this->soap);
#else
			return soap_send_fault(this->soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this->soap);
		soap_end(this->soap);
	} while (1);
#else
	} while (this->soap->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___ns6__GetServiceCapabilities(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetAuthenticationProfileInfo(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetAuthenticationProfileInfoList(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetAuthenticationProfiles(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetAuthenticationProfileList(AuthenticationBehaviorBindingService*);
static int serve___ns6__CreateAuthenticationProfile(AuthenticationBehaviorBindingService*);
static int serve___ns6__SetAuthenticationProfile(AuthenticationBehaviorBindingService*);
static int serve___ns6__ModifyAuthenticationProfile(AuthenticationBehaviorBindingService*);
static int serve___ns6__DeleteAuthenticationProfile(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetSecurityLevelInfo(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetSecurityLevelInfoList(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetSecurityLevels(AuthenticationBehaviorBindingService*);
static int serve___ns6__GetSecurityLevelList(AuthenticationBehaviorBindingService*);
static int serve___ns6__CreateSecurityLevel(AuthenticationBehaviorBindingService*);
static int serve___ns6__SetSecurityLevel(AuthenticationBehaviorBindingService*);
static int serve___ns6__ModifySecurityLevel(AuthenticationBehaviorBindingService*);
static int serve___ns6__DeleteSecurityLevel(AuthenticationBehaviorBindingService*);

int AuthenticationBehaviorBindingService::dispatch()
{	AuthenticationBehaviorBindingService_init(this->soap->imode, this->soap->omode);
	soap_peek_element(this->soap);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetServiceCapabilities"))
		return serve___ns6__GetServiceCapabilities(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetAuthenticationProfileInfo"))
		return serve___ns6__GetAuthenticationProfileInfo(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetAuthenticationProfileInfoList"))
		return serve___ns6__GetAuthenticationProfileInfoList(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetAuthenticationProfiles"))
		return serve___ns6__GetAuthenticationProfiles(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetAuthenticationProfileList"))
		return serve___ns6__GetAuthenticationProfileList(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:CreateAuthenticationProfile"))
		return serve___ns6__CreateAuthenticationProfile(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:SetAuthenticationProfile"))
		return serve___ns6__SetAuthenticationProfile(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:ModifyAuthenticationProfile"))
		return serve___ns6__ModifyAuthenticationProfile(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:DeleteAuthenticationProfile"))
		return serve___ns6__DeleteAuthenticationProfile(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetSecurityLevelInfo"))
		return serve___ns6__GetSecurityLevelInfo(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetSecurityLevelInfoList"))
		return serve___ns6__GetSecurityLevelInfoList(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetSecurityLevels"))
		return serve___ns6__GetSecurityLevels(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:GetSecurityLevelList"))
		return serve___ns6__GetSecurityLevelList(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:CreateSecurityLevel"))
		return serve___ns6__CreateSecurityLevel(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:SetSecurityLevel"))
		return serve___ns6__SetSecurityLevel(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:ModifySecurityLevel"))
		return serve___ns6__ModifySecurityLevel(this);
	if (!soap_match_tag(this->soap, this->soap->tag, "ns6:DeleteSecurityLevel"))
		return serve___ns6__DeleteSecurityLevel(this);
	return this->soap->error = SOAP_NO_METHOD;
}

static int serve___ns6__GetServiceCapabilities(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetServiceCapabilities soap_tmp___ns6__GetServiceCapabilities;
	_ns6__GetServiceCapabilitiesResponse ns6__GetServiceCapabilitiesResponse;
	ns6__GetServiceCapabilitiesResponse.soap_default(soap);
	soap_default___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities);
	if (!soap_get___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities, "-ns6:GetServiceCapabilities", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetServiceCapabilities(soap_tmp___ns6__GetServiceCapabilities.ns6__GetServiceCapabilities, &ns6__GetServiceCapabilitiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetServiceCapabilitiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetServiceCapabilitiesResponse.soap_put(soap, "ns6:GetServiceCapabilitiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetServiceCapabilitiesResponse.soap_put(soap, "ns6:GetServiceCapabilitiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetAuthenticationProfileInfo(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetAuthenticationProfileInfo soap_tmp___ns6__GetAuthenticationProfileInfo;
	_ns6__GetAuthenticationProfileInfoResponse ns6__GetAuthenticationProfileInfoResponse;
	ns6__GetAuthenticationProfileInfoResponse.soap_default(soap);
	soap_default___ns6__GetAuthenticationProfileInfo(soap, &soap_tmp___ns6__GetAuthenticationProfileInfo);
	if (!soap_get___ns6__GetAuthenticationProfileInfo(soap, &soap_tmp___ns6__GetAuthenticationProfileInfo, "-ns6:GetAuthenticationProfileInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetAuthenticationProfileInfo(soap_tmp___ns6__GetAuthenticationProfileInfo.ns6__GetAuthenticationProfileInfo, &ns6__GetAuthenticationProfileInfoResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetAuthenticationProfileInfoResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetAuthenticationProfileInfoResponse.soap_put(soap, "ns6:GetAuthenticationProfileInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetAuthenticationProfileInfoResponse.soap_put(soap, "ns6:GetAuthenticationProfileInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetAuthenticationProfileInfoList(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetAuthenticationProfileInfoList soap_tmp___ns6__GetAuthenticationProfileInfoList;
	_ns6__GetAuthenticationProfileInfoListResponse ns6__GetAuthenticationProfileInfoListResponse;
	ns6__GetAuthenticationProfileInfoListResponse.soap_default(soap);
	soap_default___ns6__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns6__GetAuthenticationProfileInfoList);
	if (!soap_get___ns6__GetAuthenticationProfileInfoList(soap, &soap_tmp___ns6__GetAuthenticationProfileInfoList, "-ns6:GetAuthenticationProfileInfoList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetAuthenticationProfileInfoList(soap_tmp___ns6__GetAuthenticationProfileInfoList.ns6__GetAuthenticationProfileInfoList, &ns6__GetAuthenticationProfileInfoListResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetAuthenticationProfileInfoListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetAuthenticationProfileInfoListResponse.soap_put(soap, "ns6:GetAuthenticationProfileInfoListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetAuthenticationProfileInfoListResponse.soap_put(soap, "ns6:GetAuthenticationProfileInfoListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetAuthenticationProfiles(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetAuthenticationProfiles soap_tmp___ns6__GetAuthenticationProfiles;
	_ns6__GetAuthenticationProfilesResponse ns6__GetAuthenticationProfilesResponse;
	ns6__GetAuthenticationProfilesResponse.soap_default(soap);
	soap_default___ns6__GetAuthenticationProfiles(soap, &soap_tmp___ns6__GetAuthenticationProfiles);
	if (!soap_get___ns6__GetAuthenticationProfiles(soap, &soap_tmp___ns6__GetAuthenticationProfiles, "-ns6:GetAuthenticationProfiles", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetAuthenticationProfiles(soap_tmp___ns6__GetAuthenticationProfiles.ns6__GetAuthenticationProfiles, &ns6__GetAuthenticationProfilesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetAuthenticationProfilesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetAuthenticationProfilesResponse.soap_put(soap, "ns6:GetAuthenticationProfilesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetAuthenticationProfilesResponse.soap_put(soap, "ns6:GetAuthenticationProfilesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetAuthenticationProfileList(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetAuthenticationProfileList soap_tmp___ns6__GetAuthenticationProfileList;
	_ns6__GetAuthenticationProfileListResponse ns6__GetAuthenticationProfileListResponse;
	ns6__GetAuthenticationProfileListResponse.soap_default(soap);
	soap_default___ns6__GetAuthenticationProfileList(soap, &soap_tmp___ns6__GetAuthenticationProfileList);
	if (!soap_get___ns6__GetAuthenticationProfileList(soap, &soap_tmp___ns6__GetAuthenticationProfileList, "-ns6:GetAuthenticationProfileList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetAuthenticationProfileList(soap_tmp___ns6__GetAuthenticationProfileList.ns6__GetAuthenticationProfileList, &ns6__GetAuthenticationProfileListResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetAuthenticationProfileListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetAuthenticationProfileListResponse.soap_put(soap, "ns6:GetAuthenticationProfileListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetAuthenticationProfileListResponse.soap_put(soap, "ns6:GetAuthenticationProfileListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__CreateAuthenticationProfile(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__CreateAuthenticationProfile soap_tmp___ns6__CreateAuthenticationProfile;
	_ns6__CreateAuthenticationProfileResponse ns6__CreateAuthenticationProfileResponse;
	ns6__CreateAuthenticationProfileResponse.soap_default(soap);
	soap_default___ns6__CreateAuthenticationProfile(soap, &soap_tmp___ns6__CreateAuthenticationProfile);
	if (!soap_get___ns6__CreateAuthenticationProfile(soap, &soap_tmp___ns6__CreateAuthenticationProfile, "-ns6:CreateAuthenticationProfile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->CreateAuthenticationProfile(soap_tmp___ns6__CreateAuthenticationProfile.ns6__CreateAuthenticationProfile, &ns6__CreateAuthenticationProfileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__CreateAuthenticationProfileResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__CreateAuthenticationProfileResponse.soap_put(soap, "ns6:CreateAuthenticationProfileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__CreateAuthenticationProfileResponse.soap_put(soap, "ns6:CreateAuthenticationProfileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__SetAuthenticationProfile(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__SetAuthenticationProfile soap_tmp___ns6__SetAuthenticationProfile;
	_ns6__SetAuthenticationProfileResponse ns6__SetAuthenticationProfileResponse;
	ns6__SetAuthenticationProfileResponse.soap_default(soap);
	soap_default___ns6__SetAuthenticationProfile(soap, &soap_tmp___ns6__SetAuthenticationProfile);
	if (!soap_get___ns6__SetAuthenticationProfile(soap, &soap_tmp___ns6__SetAuthenticationProfile, "-ns6:SetAuthenticationProfile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetAuthenticationProfile(soap_tmp___ns6__SetAuthenticationProfile.ns6__SetAuthenticationProfile, &ns6__SetAuthenticationProfileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__SetAuthenticationProfileResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__SetAuthenticationProfileResponse.soap_put(soap, "ns6:SetAuthenticationProfileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__SetAuthenticationProfileResponse.soap_put(soap, "ns6:SetAuthenticationProfileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__ModifyAuthenticationProfile(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__ModifyAuthenticationProfile soap_tmp___ns6__ModifyAuthenticationProfile;
	_ns6__ModifyAuthenticationProfileResponse ns6__ModifyAuthenticationProfileResponse;
	ns6__ModifyAuthenticationProfileResponse.soap_default(soap);
	soap_default___ns6__ModifyAuthenticationProfile(soap, &soap_tmp___ns6__ModifyAuthenticationProfile);
	if (!soap_get___ns6__ModifyAuthenticationProfile(soap, &soap_tmp___ns6__ModifyAuthenticationProfile, "-ns6:ModifyAuthenticationProfile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->ModifyAuthenticationProfile(soap_tmp___ns6__ModifyAuthenticationProfile.ns6__ModifyAuthenticationProfile, &ns6__ModifyAuthenticationProfileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__ModifyAuthenticationProfileResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__ModifyAuthenticationProfileResponse.soap_put(soap, "ns6:ModifyAuthenticationProfileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__ModifyAuthenticationProfileResponse.soap_put(soap, "ns6:ModifyAuthenticationProfileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__DeleteAuthenticationProfile(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__DeleteAuthenticationProfile soap_tmp___ns6__DeleteAuthenticationProfile;
	_ns6__DeleteAuthenticationProfileResponse ns6__DeleteAuthenticationProfileResponse;
	ns6__DeleteAuthenticationProfileResponse.soap_default(soap);
	soap_default___ns6__DeleteAuthenticationProfile(soap, &soap_tmp___ns6__DeleteAuthenticationProfile);
	if (!soap_get___ns6__DeleteAuthenticationProfile(soap, &soap_tmp___ns6__DeleteAuthenticationProfile, "-ns6:DeleteAuthenticationProfile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->DeleteAuthenticationProfile(soap_tmp___ns6__DeleteAuthenticationProfile.ns6__DeleteAuthenticationProfile, &ns6__DeleteAuthenticationProfileResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__DeleteAuthenticationProfileResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__DeleteAuthenticationProfileResponse.soap_put(soap, "ns6:DeleteAuthenticationProfileResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__DeleteAuthenticationProfileResponse.soap_put(soap, "ns6:DeleteAuthenticationProfileResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetSecurityLevelInfo(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetSecurityLevelInfo soap_tmp___ns6__GetSecurityLevelInfo;
	_ns6__GetSecurityLevelInfoResponse ns6__GetSecurityLevelInfoResponse;
	ns6__GetSecurityLevelInfoResponse.soap_default(soap);
	soap_default___ns6__GetSecurityLevelInfo(soap, &soap_tmp___ns6__GetSecurityLevelInfo);
	if (!soap_get___ns6__GetSecurityLevelInfo(soap, &soap_tmp___ns6__GetSecurityLevelInfo, "-ns6:GetSecurityLevelInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetSecurityLevelInfo(soap_tmp___ns6__GetSecurityLevelInfo.ns6__GetSecurityLevelInfo, &ns6__GetSecurityLevelInfoResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetSecurityLevelInfoResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetSecurityLevelInfoResponse.soap_put(soap, "ns6:GetSecurityLevelInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetSecurityLevelInfoResponse.soap_put(soap, "ns6:GetSecurityLevelInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetSecurityLevelInfoList(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetSecurityLevelInfoList soap_tmp___ns6__GetSecurityLevelInfoList;
	_ns6__GetSecurityLevelInfoListResponse ns6__GetSecurityLevelInfoListResponse;
	ns6__GetSecurityLevelInfoListResponse.soap_default(soap);
	soap_default___ns6__GetSecurityLevelInfoList(soap, &soap_tmp___ns6__GetSecurityLevelInfoList);
	if (!soap_get___ns6__GetSecurityLevelInfoList(soap, &soap_tmp___ns6__GetSecurityLevelInfoList, "-ns6:GetSecurityLevelInfoList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetSecurityLevelInfoList(soap_tmp___ns6__GetSecurityLevelInfoList.ns6__GetSecurityLevelInfoList, &ns6__GetSecurityLevelInfoListResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetSecurityLevelInfoListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetSecurityLevelInfoListResponse.soap_put(soap, "ns6:GetSecurityLevelInfoListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetSecurityLevelInfoListResponse.soap_put(soap, "ns6:GetSecurityLevelInfoListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetSecurityLevels(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetSecurityLevels soap_tmp___ns6__GetSecurityLevels;
	_ns6__GetSecurityLevelsResponse ns6__GetSecurityLevelsResponse;
	ns6__GetSecurityLevelsResponse.soap_default(soap);
	soap_default___ns6__GetSecurityLevels(soap, &soap_tmp___ns6__GetSecurityLevels);
	if (!soap_get___ns6__GetSecurityLevels(soap, &soap_tmp___ns6__GetSecurityLevels, "-ns6:GetSecurityLevels", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetSecurityLevels(soap_tmp___ns6__GetSecurityLevels.ns6__GetSecurityLevels, &ns6__GetSecurityLevelsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetSecurityLevelsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetSecurityLevelsResponse.soap_put(soap, "ns6:GetSecurityLevelsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetSecurityLevelsResponse.soap_put(soap, "ns6:GetSecurityLevelsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__GetSecurityLevelList(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__GetSecurityLevelList soap_tmp___ns6__GetSecurityLevelList;
	_ns6__GetSecurityLevelListResponse ns6__GetSecurityLevelListResponse;
	ns6__GetSecurityLevelListResponse.soap_default(soap);
	soap_default___ns6__GetSecurityLevelList(soap, &soap_tmp___ns6__GetSecurityLevelList);
	if (!soap_get___ns6__GetSecurityLevelList(soap, &soap_tmp___ns6__GetSecurityLevelList, "-ns6:GetSecurityLevelList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetSecurityLevelList(soap_tmp___ns6__GetSecurityLevelList.ns6__GetSecurityLevelList, &ns6__GetSecurityLevelListResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__GetSecurityLevelListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__GetSecurityLevelListResponse.soap_put(soap, "ns6:GetSecurityLevelListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__GetSecurityLevelListResponse.soap_put(soap, "ns6:GetSecurityLevelListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__CreateSecurityLevel(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__CreateSecurityLevel soap_tmp___ns6__CreateSecurityLevel;
	_ns6__CreateSecurityLevelResponse ns6__CreateSecurityLevelResponse;
	ns6__CreateSecurityLevelResponse.soap_default(soap);
	soap_default___ns6__CreateSecurityLevel(soap, &soap_tmp___ns6__CreateSecurityLevel);
	if (!soap_get___ns6__CreateSecurityLevel(soap, &soap_tmp___ns6__CreateSecurityLevel, "-ns6:CreateSecurityLevel", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->CreateSecurityLevel(soap_tmp___ns6__CreateSecurityLevel.ns6__CreateSecurityLevel, &ns6__CreateSecurityLevelResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__CreateSecurityLevelResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__CreateSecurityLevelResponse.soap_put(soap, "ns6:CreateSecurityLevelResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__CreateSecurityLevelResponse.soap_put(soap, "ns6:CreateSecurityLevelResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__SetSecurityLevel(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__SetSecurityLevel soap_tmp___ns6__SetSecurityLevel;
	_ns6__SetSecurityLevelResponse ns6__SetSecurityLevelResponse;
	ns6__SetSecurityLevelResponse.soap_default(soap);
	soap_default___ns6__SetSecurityLevel(soap, &soap_tmp___ns6__SetSecurityLevel);
	if (!soap_get___ns6__SetSecurityLevel(soap, &soap_tmp___ns6__SetSecurityLevel, "-ns6:SetSecurityLevel", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetSecurityLevel(soap_tmp___ns6__SetSecurityLevel.ns6__SetSecurityLevel, &ns6__SetSecurityLevelResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__SetSecurityLevelResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__SetSecurityLevelResponse.soap_put(soap, "ns6:SetSecurityLevelResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__SetSecurityLevelResponse.soap_put(soap, "ns6:SetSecurityLevelResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__ModifySecurityLevel(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__ModifySecurityLevel soap_tmp___ns6__ModifySecurityLevel;
	_ns6__ModifySecurityLevelResponse ns6__ModifySecurityLevelResponse;
	ns6__ModifySecurityLevelResponse.soap_default(soap);
	soap_default___ns6__ModifySecurityLevel(soap, &soap_tmp___ns6__ModifySecurityLevel);
	if (!soap_get___ns6__ModifySecurityLevel(soap, &soap_tmp___ns6__ModifySecurityLevel, "-ns6:ModifySecurityLevel", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->ModifySecurityLevel(soap_tmp___ns6__ModifySecurityLevel.ns6__ModifySecurityLevel, &ns6__ModifySecurityLevelResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__ModifySecurityLevelResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__ModifySecurityLevelResponse.soap_put(soap, "ns6:ModifySecurityLevelResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__ModifySecurityLevelResponse.soap_put(soap, "ns6:ModifySecurityLevelResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns6__DeleteSecurityLevel(AuthenticationBehaviorBindingService *service)
{	struct soap *soap = service->soap;
	struct __ns6__DeleteSecurityLevel soap_tmp___ns6__DeleteSecurityLevel;
	_ns6__DeleteSecurityLevelResponse ns6__DeleteSecurityLevelResponse;
	ns6__DeleteSecurityLevelResponse.soap_default(soap);
	soap_default___ns6__DeleteSecurityLevel(soap, &soap_tmp___ns6__DeleteSecurityLevel);
	if (!soap_get___ns6__DeleteSecurityLevel(soap, &soap_tmp___ns6__DeleteSecurityLevel, "-ns6:DeleteSecurityLevel", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->DeleteSecurityLevel(soap_tmp___ns6__DeleteSecurityLevel.ns6__DeleteSecurityLevel, &ns6__DeleteSecurityLevelResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ns6__DeleteSecurityLevelResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns6__DeleteSecurityLevelResponse.soap_put(soap, "ns6:DeleteSecurityLevelResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns6__DeleteSecurityLevelResponse.soap_put(soap, "ns6:DeleteSecurityLevelResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
